apiVersion: v1
kind: Service
metadata:
  name: httpserver
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: httpserver
  namespace: default
spec:
  selector:
    app: httpserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort